export const countryList = [
    { value: "af", label: "Afghanistan" },
    { value: "alu", label: "Alabama" },
    { value: "aku", label: "Alaska" },
    { value: "aa", label: "Albania" },
    { value: "abc", label: "Alberta" },
    { value: "ae", label: "Algeria" },
    { value: "as", label: "American Samoa" },
    { value: "an", label: "Andorra" },
    { value: "ao", label: "Angola" },
    { value: "am", label: "Anguilla" },
    { value: "ay", label: "Antarctica" },
    { value: "aq", label: "Antigua and Barbuda" },
    { value: "ag", label: "Argentina" },
    { value: "azu", label: "Arizona" },
    { value: "aru", label: "Arkansas" },
    { value: "ai", label: "Armenia (Republic)" },
    { value: "aw", label: "Aruba" },
    { value: "at", label: "Australia" },
    { value: "aca", label: "Australian Capital Territory" },
    { value: "au", label: "Austria" },
    { value: "aj", label: "Azerbaijan" },
    { value: "bf", label: "Bahamas" },
    { value: "ba", label: "Bahrain" },
    { value: "bg", label: "Bangladesh" },
    { value: "bb", label: "Barbados" },
    { value: "bw", label: "Belarus" },
    { value: "be", label: "Belgium" },
    { value: "bh", label: "Belize" },
    { value: "dm", label: "Benin" },
    { value: "bm", label: "Bermuda Islands" },
    { value: "bt", label: "Bhutan" },
    { value: "bo", label: "Bolivia" },
    { value: "bn", label: "Bosnia and Hercegovina" },
    { value: "bs", label: "Botswana" },
    { value: "bv", label: "Bouvet Island" },
    { value: "bl", label: "Brazil" },
    { value: "bcc", label: "British Columbia" },
    { value: "bi", label: "British Indian Ocean Territory" },
    { value: "vb", label: "British Virgin Islands" },
    { value: "bx", label: "Brunei" },
    { value: "bu", label: "Bulgaria" },
    { value: "uv", label: "Burkina Faso" },
    { value: "br", label: "Burma" },
    { value: "bd", label: "Burundi" },
    { value: "cv", label: "Cabo Verde" },
    { value: "cau", label: "California" },
    { value: "cb", label: "Cambodia" },
    { value: "cm", label: "Cameroon" },
    { value: "xxc", label: "Canada" },
    { value: "ca", label: "Caribbean Netherlands" },
    { value: "cj", label: "Cayman Islands" },
    { value: "cx", label: "Central African Republic" },
    { value: "cd", label: "Chad" },
    { value: "cl", label: "Chile" },
    { value: "cc", label: "China" },
    { value: "ch", label: "China (Republic : 1949- )" },
    { value: "xa", label: "Christmas Island (Indian Ocean)" },
    { value: "xb", label: "Cocos (Keeling) Islands" },
    { value: "ck", label: "Colombia" },
    { value: "cou", label: "Colorado" },
    { value: "cq", label: "Comoros" },
    { value: "cf", label: "Congo (Brazzaville)" },
    { value: "cg", label: "Congo (Democratic Republic)" },
    { value: "ctu", label: "Connecticut" },
    { value: "cw", label: "Cook Islands" },
    { value: "xga", label: "Coral Sea Islands Territory" },
    { value: "cr", label: "Costa Rica" },
    { value: "iv", label: "Côte d'Ivoire" },
    { value: "ci", label: "Croatia" },
    { value: "cu", label: "Cuba" },
    { value: "co", label: "Curaçao" },
    { value: "cy", label: "Cyprus" },
    { value: "xr", label: "Czech Republic" },
    { value: "deu", label: "Delaware" },
    { value: "dk", label: "Denmark" },
    { value: "dcu", label: "District of Columbia" },
    { value: "ft", label: "Djibouti" },
    { value: "dq", label: "Dominica" },
    { value: "dr", label: "Dominican Republic" },
    { value: "ec", label: "Ecuador" },
    { value: "ua", label: "Egypt" },
    { value: "es", label: "El Salvador" },
    { value: "enk", label: "England" },
    { value: "eg", label: "Equatorial Guinea" },
    { value: "ea", label: "Eritrea" },
    { value: "er", label: "Estonia" },
    { value: "et", label: "Ethiopia" },
    { value: "fk", label: "Falkland Islands" },
    { value: "fa", label: "Faroe Islands" },
    { value: "fj", label: "Fiji" },
    { value: "fi", label: "Finland" },
    { value: "flu", label: "Florida" },
    { value: "fr", label: "France" },
    { value: "fg", label: "French Guiana" },
    { value: "fp", label: "French Polynesia" },
    { value: "go", label: "Gabon" },
    { value: "gm", label: "Gambia" },
    { value: "gz", label: "Gaza Strip" },
    { value: "gau", label: "Georgia" },
    { value: "gs", label: "Georgia (Republic)" },
    { value: "gw", label: "Germany" },
    { value: "gh", label: "Ghana" },
    { value: "gi", label: "Gibraltar" },
    { value: "gr", label: "Greece" },
    { value: "gl", label: "Greenland" },
    { value: "gd", label: "Grenada" },
    { value: "gp", label: "Guadeloupe" },
    { value: "gu", label: "Guam" },
    { value: "gt", label: "Guatemala" },
    { value: "gv", label: "Guinea" },
    { value: "pg", label: "Guinea-Bissau" },
    { value: "gy", label: "Guyana" },
    { value: "ht", label: "Haiti" },
    { value: "hiu", label: "Hawaii" },
    { value: "hm", label: "Heard and McDonald Islands" },
    { value: "ho", label: "Honduras" },
    { value: "hu", label: "Hungary" },
    { value: "ic", label: "Iceland" },
    { value: "idu", label: "Idaho" },
    { value: "ilu", label: "Illinois" },
    { value: "ii", label: "India" },
    { value: "inu", label: "Indiana" },
    { value: "io", label: "Indonesia" },
    { value: "iau", label: "Iowa" },
    { value: "ir", label: "Iran" },
    { value: "iq", label: "Iraq" },
    { value: "iy", label: "Iraq-Saudi Arabia Neutral Zone" },
    { value: "ie", label: "Ireland" },
    { value: "is", label: "Israel" },
    { value: "it", label: "Italy" },
    { value: "jm", label: "Jamaica" },
    { value: "ja", label: "Japan" },
    { value: "ji", label: "Johnston Atoll" },
    { value: "jo", label: "Jordan" },
    { value: "ksu", label: "Kansas" },
    { value: "kz", label: "Kazakhstan" },
    { value: "kyu", label: "Kentucky" },
    { value: "ke", label: "Kenya" },
    { value: "gb", label: "Kiribati" },
    { value: "kn", label: "Korea (North)" },
    { value: "ko", label: "Korea (South)" },
    { value: "kv", label: "Kosovo" },
    { value: "ku", label: "Kuwait" },
    { value: "kg", label: "Kyrgyzstan" },
    { value: "ls", label: "Laos" },
    { value: "lv", label: "Latvia" },
    { value: "le", label: "Lebanon" },
    { value: "lo", label: "Lesotho" },
    { value: "lb", label: "Liberia" },
    { value: "ly", label: "Libya" },
    { value: "lh", label: "Liechtenstein" },
    { value: "li", label: "Lithuania" },
    { value: "lau", label: "Louisiana" },
    { value: "lu", label: "Luxembourg" },
    { value: "xn", label: "Macedonia" },
    { value: "mg", label: "Madagascar" },
    { value: "meu", label: "Maine" },
    { value: "mw", label: "Malawi" },
    { value: "my", label: "Malaysia" },
    { value: "xc", label: "Maldives" },
    { value: "ml", label: "Mali" },
    { value: "mm", label: "Malta" },
    { value: "mbc", label: "Manitoba" },
    { value: "xe", label: "Marshall Islands" },
    { value: "mq", label: "Martinique" },
    { value: "mdu", label: "Maryland" },
    { value: "mau", label: "Massachusetts" },
    { value: "mu", label: "Mauritania" },
    { value: "mf", label: "Mauritius" },
    { value: "ot", label: "Mayotte" },
    { value: "mx", label: "Mexico" },
    { value: "miu", label: "Michigan" },
    { value: "fm", label: "Micronesia (Federated States)" },
    { value: "xf", label: "Midway Islands" },
    { value: "mnu", label: "Minnesota" },
    { value: "msu", label: "Mississippi" },
    { value: "mou", label: "Missouri" },
    { value: "mv", label: "Moldova" },
    { value: "mc", label: "Monaco" },
    { value: "mp", label: "Mongolia" },
    { value: "mtu", label: "Montana" },
    { value: "mo", label: "Montenegro" },
    { value: "mj", label: "Montserrat" },
    { value: "mr", label: "Morocco" },
    { value: "mz", label: "Mozambique" },
    { value: "sx", label: "Namibia" },
    { value: "nu", label: "Nauru" },
    { value: "nbu", label: "Nebraska" },
    { value: "np", label: "Nepal" },
    { value: "ne", label: "Netherlands" },
    { value: "nvu", label: "Nevada" },
    { value: "nkc", label: "New Brunswick" },
    { value: "nl", label: "New Caledonia" },
    { value: "nhu", label: "New Hampshire" },
    { value: "nju", label: "New Jersey" },
    { value: "nmu", label: "New Mexico" },
    { value: "xna", label: "New South Wales" },
    { value: "nyu", label: "New York (State)" },
    { value: "nz", label: "New Zealand" },
    { value: "nfc", label: "Newfoundland and Labrador" },
    { value: "nq", label: "Nicaragua" },
    { value: "ng", label: "Niger" },
    { value: "nr", label: "Nigeria" },
    { value: "xh", label: "Niue" },
    { value: "xx", label: "No place, unknown, or undetermined" },
    { value: "nx", label: "Norfolk Island" },
    { value: "ncu", label: "North Carolina" },
    { value: "ndu", label: "North Dakota" },
    { value: "nik", label: "Northern Ireland" },
    { value: "nw", label: "Northern Mariana Islands" },
    { value: "xoa", label: "Northern Territory" },
    { value: "ntc", label: "Northwest Territories" },
    { value: "no", label: "Norway" },
    { value: "nsc", label: "Nova Scotia" },
    { value: "nuc", label: "Nunavut" },
    { value: "ohu", label: "Ohio" },
    { value: "oku", label: "Oklahoma" },
    { value: "mk", label: "Oman" },
    { value: "onc", label: "Ontario" },
    { value: "oru", label: "Oregon" },
    { value: "pk", label: "Pakistan" },
    { value: "pw", label: "Palau" },
    { value: "pn", label: "Panama" },
    { value: "pp", label: "Papua New Guinea" },
    { value: "pf", label: "Paracel Islands" },
    { value: "py", label: "Paraguay" },
    { value: "pau", label: "Pennsylvania" },
    { value: "pe", label: "Peru" },
    { value: "ph", label: "Philippines" },
    { value: "pc", label: "Pitcairn Island" },
    { value: "pl", label: "Poland" },
    { value: "po", label: "Portugal" },
    { value: "pic", label: "Prince Edward Island" },
    { value: "pr", label: "Puerto Rico" },
    { value: "qa", label: "Qatar" },
    { value: "quc", label: "Québec (Province)" },
    { value: "qea", label: "Queensland" },
    { value: "re", label: "Réunion" },
    { value: "riu", label: "Rhode Island" },
    { value: "rm", label: "Romania" },
    { value: "ru", label: "Russia (Federation)" },
    { value: "rw", label: "Rwanda" },
    { value: "xj", label: "Saint Helena" },
    { value: "xd", label: "Saint Kitts-Nevis" },
    { value: "xk", label: "Saint Lucia" },
    { value: "xl", label: "Saint Pierre and Miquelon" },
    { value: "xm", label: "Saint Vincent and the Grenadines" },
    { value: "sc", label: "Saint-Barthélemy" },
    { value: "st", label: "Saint-Martin" },
    { value: "ws", label: "Samoa" },
    { value: "sm", label: "San Marino" },
    { value: "sf", label: "Sao Tome and Principe" },
    { value: "snc", label: "Saskatchewan" },
    { value: "su", label: "Saudi Arabia" },
    { value: "stk", label: "Scotland" },
    { value: "sg", label: "Senegal" },
    { value: "rb", label: "Serbia" },
    { value: "se", label: "Seychelles" },
    { value: "sl", label: "Sierra Leone" },
    { value: "si", label: "Singapore" },
    { value: "sn", label: "Sint Maarten" },
    { value: "xo", label: "Slovakia" },
    { value: "xv", label: "Slovenia" },
    { value: "bp", label: "Solomon Islands" },
    { value: "so", label: "Somalia" },
    { value: "sa", label: "South Africa" },
    { value: "xra", label: "South Australia" },
    { value: "scu", label: "South Carolina" },
    { value: "sdu", label: "South Dakota" },
    { value: "xs", label: "South Georgia and the South Sandwich Islands" },
    { value: "sd", label: "South Sudan" },
    { value: "sp", label: "Spain" },
    { value: "sh", label: "Spanish North Africa" },
    { value: "xp", label: "Spratly Island" },
    { value: "ce", label: "Sri Lanka" },
    { value: "sj", label: "Sudan" },
    { value: "sr", label: "Surinam" },
    { value: "sq", label: "Swaziland" },
    { value: "sw", label: "Sweden" },
    { value: "sz", label: "Switzerland" },
    { value: "sy", label: "Syria" },
    { value: "ta", label: "Tajikistan" },
    { value: "tz", label: "Tanzania" },
    { value: "tma", label: "Tasmania" },
    { value: "tnu", label: "Tennessee" },
    { value: "fs", label: "Terres australes et antarctiques françaises" },
    { value: "txu", label: "Texas" },
    { value: "th", label: "Thailand" },
    { value: "em", label: "Timor-Leste" },
    { value: "tg", label: "Togo" },
    { value: "tl", label: "Tokelau" },
    { value: "to", label: "Tonga" },
    { value: "tr", label: "Trinidad and Tobago" },
    { value: "ti", label: "Tunisia" },
    { value: "tu", label: "Turkey" },
    { value: "tk", label: "Turkmenistan" },
    { value: "tc", label: "Turks and Caicos Islands" },
    { value: "tv", label: "Tuvalu" },
    { value: "ug", label: "Uganda" },
    { value: "un", label: "Ukraine" },
    { value: "ts", label: "United Arab Emirates" },
    { value: "xxk", label: "United Kingdom" },
    { value: "uik", label: "United Kingdom Misc. Islands" },
    { value: "xxu", label: "United States" },
    { value: "uc", label: "United States Misc. Caribbean Islands" },
    { value: "up", label: "United States Misc. Pacific Islands" },
    { value: "uy", label: "Uruguay" },
    { value: "utu", label: "Utah" },
    { value: "uz", label: "Uzbekistan" },
    { value: "nn", label: "Vanuatu" },
    { value: "vp", label: "Various places" },
    { value: "vc", label: "Vatican City" },
    { value: "ve", label: "Venezuela" },
    { value: "vtu", label: "Vermont" },
    { value: "vra", label: "Victoria" },
    { value: "vm", label: "Vietnam" },
    { value: "vi", label: "Virgin Islands of the United States" },
    { value: "vau", label: "Virginia" },
    { value: "wk", label: "Wake Island" },
    { value: "wlk", label: "Wales" },
    { value: "wf", label: "Wallis and Futuna" },
    { value: "wau", label: "Washington (State)" },
    { value: "wj", label: "West Bank of the Jordan River" },
    { value: "wvu", label: "West Virginia" },
    { value: "wea", label: "Western Australia" },
    { value: "ss", label: "Western Sahara" },
    { value: "wiu", label: "Wisconsin" },
    { value: "wyu", label: "Wyoming" },
    { value: "ye", label: "Yemen" },
    { value: "ykc", label: "Yukon Territory" },
    { value: "za", label: "Zambia" },
    { value: "rh", label: "Zimbabwe" }
];
