export const frequencyList = [
    { value: '#', label: 'No determinable frequency' },
    { value: 'a', label: 'Annual' },
    { value: 'b', label: 'Bimonthly' },
    { value: 'c', label: 'Semiweekly' },
    { value: 'd', label: 'Daily' },
    { value: 'e', label: 'Biweekly' },
    { value: 'f', label: 'Semiannual' },
    { value: 'g', label: 'Biennial' },
    { value: 'h', label: 'Triennial' },
    { value: 'i', label: 'Three times a week' },
    { value: 'j', label: 'Three times a month' },
    { value: 'k', label: 'Continuously updated' },
    { value: 'm', label: 'Monthly' },
    { value: 'q', label: 'Quarterly' },
    { value: 's', label: 'Semimonthly' },
    { value: 't', label: 'Three times a year' },
    { value: 'u', label: 'Unknown' },
    { value: 'w', label: 'Weekly' },
    { value: 'z', label: 'Other' },
    { value: 'n', label: 'Normalized irregular' },
    { value: 'r', label: 'Regular' },
    { value: 'x', label: 'Completely irregular' }
];
