export const stateList = [
    { value: "alu", label: "Alabama" },
    { value: "aku", label: "Alaska" },
    { value: "azu", label: "Arizona" },
    { value: "aru", label: "Arkansas" },
    { value: "cau", label: "California" },
    { value: "cou", label: "Colorado" },
    { value: "ctu", label: "Connecticut" },
    { value: "deu", label: "Delaware" },
    { value: "dcu", label: "District of Columbia" },
    { value: "flu", label: "Florida" },
    { value: "gau", label: "Georgia" },
    { value: "hiu", label: "Hawaii" },
    { value: "idu", label: "Idaho" },
    { value: "ilu", label: "Illinois" },
    { value: "inu", label: "Indiana" },
    { value: "iau", label: "Iowa" },
    { value: "ksu", label: "Kansas" },
    { value: "kyu", label: "Kentucky" },
    { value: "lau", label: "Louisiana" },
    { value: "meu", label: "Maine" },
    { value: "mdu", label: "Maryland" },
    { value: "mau", label: "Massachusetts" },
    { value: "miu", label: "Michigan" },
    { value: "mnu", label: "Minnesota" },
    { value: "msu", label: "Mississippi" },
    { value: "mou", label: "Missouri" },
    { value: "mtu", label: "Montana" },
    { value: "nbu", label: "Nebraska" },
    { value: "nvu", label: "Nevada" },
    { value: "nhu", label: "New Hampshire" },
    { value: "nju", label: "New Jersey" },
    { value: "nmu", label: "New Mexico" },
    { value: "nyu", label: "New York (State)" },
    { value: "ncu", label: "North Carolina" },
    { value: "ndu", label: "North Dakota" },
    { value: "ohu", label: "Ohio" },
    { value: "oku", label: "Oklahoma" },
    { value: "oru", label: "Oregon" },
    { value: "pau", label: "Pennsylvania" },
    { value: "riu", label: "Rhode Island" },
    { value: "scu", label: "South Carolina" },
    { value: "sdu", label: "South Dakota" },
    { value: "tnu", label: "Tennessee" },
    { value: "txu", label: "Texas" },
    { value: "utu", label: "Utah" },
    { value: "vtu", label: "Vermont" },
    { value: "vau", label: "Virginia" },
    { value: "wau", label: "Washington (State)" },
    { value: "wvu", label: "West Virginia" },
    { value: "wiu", label: "Wisconsin" },
    { value: "wyu", label: "Wyoming" }
];
